### PR TITLE
Fix CI broken by npm's breaking change

### PR DESCRIPTION
**Pull request by msm-code**
**Your checklist for this pull request**
- [x] I've read the [contributing guideline](https://github.com/CERT-Polska/mquery/blob/master/CONTRIBUTING.md).
- [ ] I've tested my changes by building and running mquery, and testing changed functionality (if applicable)
- [ ] I've added automated tests for my change (if applicable, optional)
- [ ] I've updated documentation to reflect my change (if applicable)

**What is the current behaviour?**
CI stopped working correctly "by itself"

**What is the new behaviour?**
CI builds without problems

**Test plan**
All the CI checks should pass 

"After submitting, your code will be tested by the CI pipeline. Please
ensure that all tests pass. If they don't at first, please update your code"

I know

### CODE REVIEW

**Comment by msm-code** [comment]
Root issue: https://github.com/npm/cli/issues/4998

**Comment by nazywam** [comment]
Probably safe to remove `temporary_file_to_force_ci` now?

**Review by nazywam — APPROVED** [review]

**Comment by nazywam** [comment]
😿

**Comment by msm-code** [comment]
:thinking: missed your comment, sorry.

Also I've removed it... locally. Forgot that `git add -a` doesn't add removed files.

Welp, another PR coming in.

**Pull request merged**
