### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by nazywam**
**Your checklist for this pull request**
- [x] I've read the [contributing guideline](https://github.com/CERT-Polska/mquery/blob/master/CONTRIBUTING.md).
- [x] I've tested my changes by building and running mquery, and testing changed functionality (if applicable)
- [ ] I've added automated tests for my change (if applicable, optional)
- [ ] I've updated documentation to reflect my change (if applicable)

**What is the current behaviour?**
Some of the dependencies are seriously outdated

**What is the new behaviour?**
Only a few of the dependencies are seriously outdated

**Test plan**
Build the frontend and check that nothing broke

**Closing issues**

---

Notable keypoints

* updating monaco broke too much stuff so I didn't touch it
* something inside react-tools broke the svg parsing and I had to replace all namespace tags and remove a <style> section - needs inspection - https://stackoverflow.com/questions/59820954/syntaxerror-unknown-namespace-tags-are-not-supported-by-default
* needed to bump the node version in dockerfile (8 is pretty ancient though)
* needed to add path module - https://stackoverflow.com/questions/50402269/module-not-found-error-cant-resolve-path

### CODE REVIEW

**Comment by msm-code** [comment]
Didn't have a chance to do a proper review&tests yet.

PR fails with:

```
> react-scripts build

Creating an optimized production build...
Failed to compile.

Module.createRequire is not a function


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mqueryfront@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
```

SO (https://stackoverflow.com/questions/70390777/error-in-module-createrequire-is-not-a-function/70392769) suggests that this is a problem with old nodejs version. Maybe bump in the dockerfile CI will fix that?

**Comment by nazywam** [comment]
Fixed the CI :1234:

**Comment by msm-code** [comment]
Testing right now :muscle:.

Can you tell me from where you get the dependabot alerts from? Is this a case of you having some special permissions than me and getting some admin-only notifications?

**Comment by msm-code** [comment]
Seems to be working fine. At least no UI problems found so far.

**Review by msm-code — APPROVED** [review]

**Pull request merged**
