### PR TITLE
Initialize the database automatically when starting mquery #402

### LINKED ISSUE #402: Initialize the database automatically when starting mquery
Currently the installation procedure is:

```
docker compose up --scale daemon=3  # this will take a while
docker compose exec web python3 -m mquery.db
```

Web container should initialize the database (run migrations) automatically.

This should happen when the *web* container is started.

Also update the documentation (remove the initialization step when it's not needed).

### PR DESCRIPTION
**Pull request by MichalJura**
**Your checklist for this pull request**
- [ ] I've read the [contributing guideline](https://github.com/CERT-Polska/mquery/blob/master/CONTRIBUTING.md).
- [ ] I've tested my changes by building and running mquery, and testing changed functionality (if applicable)
- [ ] I've added automated tests for my change (if applicable, optional)
- [ ] I've updated documentation to reflect my change (if applicable)

**What is the current behaviour?**

Currently we needed to initilize database by hand: `python3 -m mquery.db`.

**What is the new behaviour?**

Now the database initialization is automatic and it uses `alembic upgrade head` instad of `mquery.db` so it also applies migrations. Also if the database already exists it will stamp it and create `alembic_version` for future migrations to be applied via `upgrade head`

**Test plan**

For new instance:  Create new instance and it will initilize database automatically.
For existing database: Remove (unnecessary for dev containers)  web container and set it up again.
Then you can check if there is `alembic_version` in postgresql.

**Closing issues**

fixes #402

### CODE REVIEW

**Review by msm-cert — COMMENTED** [review]
This looks more complicated than I thought it would. I'll take a look at it and check if it can be simplified.

**Comment by MichalJura** [comment]
> This looks more complicated than I thought it would. I'll take a look at it and check if it can be simplified.

The reason behind it is that we don't have `alembic_version` table.
So for new instances there is no problem as `alembic upgrade head` will just apply migrations and add `alembic_version` to the database.
But if there is already a database `alemibc head upgrade` will result in error in Postrgres.
We could simply check if the database is initilized and then pass, but the new migrations like  #412  would have to be applied manually. 
On the other hand we migth want to apply them manually(but I don't think we are adding some breaking changes to the database schema?).
But in that case we could remove the stamping part.

**Comment by msm-cert** [comment]
>The reason behind it is that we don't have alembic_version table.

We should, otherwise how would previous migrations be applied?

If previous documentation was giving incorrect instructions that bypass alembic it's unfortunate, but we don't have to accomodate such weird cases (database was not a part of any released version so it's not a critical problem).

**Comment by msm-cert** [comment]
I still believe the previous version was severely overcomplicated.

Also:
image

You can't chdir to some place on disk randomly (this place is not even guaranteed to exist, it would only work with docker versions). Everything should work based on package.

Pushed some of my suggestions/fixes.

**Pull request merged**
