### PR TITLE
Plugin requirements install in web dockerfile

### PR DESCRIPTION
**Pull request by yankovs**
**Your checklist for this pull request**
- [ ] I've read the [contributing guideline](https://github.com/CERT-Polska/mquery/blob/master/CONTRIBUTING.md).
- [ ] I've tested my changes by building and running mquery, and testing changed functionality (if applicable)
- [ ] I've added automated tests for my change (if applicable, optional)
- [ ] I've updated documentation to reflect my change (if applicable)

**What is the current behaviour?**
The web dockerfile build fails in case some plugin uses a python module not present in vanilla mquery due to the use of `PluginManager` and plugin loading in `app.py`

**What is the new behaviour?**
Build is successful.

**Test plan**
Build it and see if operational. I've tested this change with a plugin that uses `boto3` and it seems to work.

### CODE REVIEW

**Comment by msm-code** [comment]
Thanks for your PR!

> The web dockerfile build fails in case some plugin uses a python module not present in vanilla mquery due to the use of PluginManager and plugin loading in app.py

Oof, right.

Would you mind also fixing `dev.web.Dockerfile`? I see that we don't install plugin dependencies there too. And maybe also add the `# plugin requirements` line to dev.daemon.Dockerfile` (just to keep things consistent).

One more idea, what do you think about changing:

```dockerfile
COPY "requirements.txt" "/tmp/requirements.txt"
RUN pip install -r /tmp/requirements.txt
# requirements.txt is added because at least one file must exist
COPY requirements.txt src/plugins/requirements-*.txt /tmp/
RUN ls /tmp/requirements-*.txt | xargs -i,, pip --no-cache-dir install -r ,,
```

To:

```dockerfile
# Copy and install main requirements.txt and plugin requirements.
COPY requirements.txt src/plugins/requirements-*.txt /tmp/
RUN ls /tmp/requirements*.txt | xargs -i,, pip --no-cache-dir install -r ,,
```

I didn't test thoroughly, but they look equivalent and I don't see a point of splitting the requirements installation process into two separate steps.

> Build it and see if operational. I've tested this change with a plugin that uses boto3 and it seems to work.

Looks like I should add requirements-s3.txt file to #327 too. And probably some tests, to catch similar misconfigurations in the docker images in the future.

This means that every official docker image we build & distribute will have (usually unnecessary) dependencies, like mwdblib and now minio. I'm inclined to accept this cost, since cost/benefit of a few megabytes more is worth lesser complexity.

**Comment by yankovs** [comment]
Just notices that the actual line is:  
```bash
RUN ls /tmp/requirements-*.txt | xargs -i,, pip --no-cache-dir install -r ,,
```  
So it'll install only files of the form `requirements-*`. The ways I see around this (all of which I think are just aesthetically different):  
- Keep as is, with 2 requirements-install blocks, with the same redundancy and comments telling the story
- Remove the `-` in the `ls`, listing all files of the form `requirements*.txt`
- Merge those two install blocks to one, something of the form:
```bash
COPY requirements.txt src/plugins/requirements-*.txt /tmp/
RUN pip install -r /tmp/requirements.txt
RUN ls /tmp/requirements-*.txt | xargs -i,, pip --no-cache-dir install -r ,,
```  

@msm-code I think it's best to just stick with one and use it, what's your favorite 🙃?

**Comment by msm-code** [comment]
>  `Remove the - in the ls, listing all files of the form requirements*.txt`

Thought about that one (I've put it in my snippet suggestion, but didn't call it out), so `ls requirements*.txt`

> @msm-code I think it's best to just stick with one and use it, what's your favorite?

I prefer the one with less docker layers, so `RUN ls /tmp/requirements*.txt | xargs -i,, pip --no-cache-dir install -r ,,`. Your third option is a tiny bit more cacheable, but don't think it's important in this use case.

**Review by msm-code — APPROVED** [review]
Looks good

**Pull request merged**
