### PR TITLE
Feature/#19 my first easy task in mquery

### LINKED ISSUE #19: Show number of total indexed files in the Status page
**Description**
The `/status` page is used to provide information about the underlying infrastructure, including versions, topology, and current connections.
If a user wants to know how many files are indexed, there's no clear way to do so (unless ursadb-cli provides it somehow, and still - it is no accessible).

My suggestion is to display the number of indexed files in the dataset(s). It will also be nice-to-have to show the number of files that aren't indexed because `ls /mnt/samples | wc -l != num_of_indexex_files`.

A bonus feature would be to show a total size of the dataset.

### PR DESCRIPTION
**Pull request by JaroPowerH**
**Your checklist for this pull request**
- [x] I've read the [contributing guideline](https://github.com/CERT-Polska/mquery/blob/master/CONTRIBUTING.md).
- [x] I've tested my changes by building and running mquery, and testing changed functionality (if applicable)
- [ ] I've added automated tests for my change (if applicable, optional)
- [ ] I've updated documentation to reflect my change (if applicable)

**What is the current behaviour?**

**What is the new behaviour?**

**Test plan**

**Closing issues**

fixes #19

### CODE REVIEW

**Comment by msm-code** [comment]
Looks good!

ss

Though not sure about adding a new column - maybe display it in the `size` column instead?

I.e. something like `2.89 GiB (50001 files)`.

Thoughts?

**Comment by JaroPowerH** [comment]
For now, displaying file count in size collumn seems to be better solution.
I can make a change.

Another issue (Display the number of files that are not indexed #42
<https://github.com/CERT-Polska/mquery/issues/42>) will need a place to
display number od file not indexed or total number od files.

We can use collumn "file count" for displaying both values.
I.e. something like 50001 of 58889.

What do you think?

Regards,
JaroPowerH

pon., 13.04.2020, 20:12 użytkownik msm-code <notifications@github.com>
napisał:

**Comment by ITAYC0HEN** [comment]
Thank you! 
So I played with it a bit. I can't tell for sure what data the team prioritizes to show the user at first sight, but this can be a clean solution.

Sod, what do you think about something like this?

mquery_show_topology_collapse2

**Comment by msm-code** [comment]
Ok, maybe first we'll merge the solution from @JaroPowerH and work on the more advanced version that you've shown later.

**Comment by JaroPowerH** [comment]
I will be pleased to work on the solution proposed by ITAYC0HEN.

**Comment by msm-code** [comment]
@ITAYC0HEN mentioned that he has some code already, so maybe  we can leave this to him.

Maybe try #94 or #35

**Pull request merged**
